config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'users#index'

  get 'users', to: 'users#index'
  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get 'users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post' # Ažurirana ruta za new akciju
  post 'users/:user_id/posts', to: 'posts#create' # Dodata ruta za create akciju
  get 'users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  get 'users/:user_id/all_posts', to: 'posts#all_posts', as: 'all_posts_user'
  get 'users/:user_id/recent_posts', to: 'posts#recent', as: 'recent_posts'

  resources :users, only: %i[index show] do
    resources :posts, except: :index do
      post 'like', on: :member
      resources :comments, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, foreign_key: 'posts_id'
  belongs_to :author, class_name: 'User'

  validates :text, presence: true

  after_create :increment_post_comments_counter

  def increment_post_comments_counter
    post.increment!(:comments_counter, 1)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post', foreign_key: 'posts_id'

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, counter_cache: true
  has_many :comments, foreign_key: 'posts_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_post_counter

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def increment_comments_counter
    increment!(:comments_counter)
  end

  def decrement_comments_counter
    decrement!(:comments_counter)
  end

  def recent_five_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.includes(:author).find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id), notice: 'Comment was successfully created.'
    else
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id), alert: 'Comment could not be saved.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.includes(:likes).find(params[:post_id])
    @like = current_user.likes.new(post: @post)

    if @like.save
      render partial: 'likes/like', locals: { post: @post }
    else
      redirect_to @post, alert: 'Failed to add like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include WillPaginate::ViewHelpers

  def index
    @user = User.find(params[:user_id])
    @all_posts = @user.posts.includes(:author).order(created_at: :desc)

    @posts = if params[:page].present?
               @all_posts
             else
               @all_posts.paginate(page: params[:page], per_page: 2)
             end
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(comments: :author).find(params[:id])
    @comments = @post.comments.includes(:author).paginate(page: params[:page], per_page: 10)
    @comments_count = @post.comments.count
    @likes_count = @post.likes.size
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(user_id: current_user.id, id: @post.id), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def new
    @user = User.find(1) # Pronalazak korisnika sa ID-om 1
    @post = @user.posts.build
  end

  def like
    @post = Post.find(params[:id])
    Like.create(post: @post, author: current_user)

    respond_to(&:js)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @posts = Post.limit(3)
  end

  def show
    if params[:id] == 'sign_out'
      # Logika za odjavu korisnika
      # Na primer, ako koristite Devise:
      sign_out(current_user)
      redirect_to root_path
    else
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_new.html.erb
<%= form_with url: user_post_comments_path(user_id: @user.id, post_id: @post.id), local: true do |form| %>
  <%= form.text_field :text, name: 'comment[text]' %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<head>
  <link rel="stylesheet" href="<%= asset_path('application.css') %>">
</head>

<div class="user">
  <div class="user-profile">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, alt: "Profile Picture", width: "100", height: "100" %>
    <% else %>
      <p>No Profile Picture</p>
    <% end %>
  </div>

  <div class="user-info">
    <h3><%= @user.name %></h3>
    <p>Number of posts: <%= @user.posts.count %></p>
  </div>
</div>

<ul>
  <% if @user.posts.present? %>
    <% @user.posts.order(created_at: :desc).paginate(page: params[:page], per_page: (params[:per_page] || 2).to_i).each_with_index do |post, index| %>
      <li class="list">
        <div class="post">
          <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
<h4><%= post.title %></h4>
          <% end %>
          <p><%= post.text %></p>
          <p>Likes: <%= post.likes_counter %></p>
          <p>Comments: <%= post.comments_counter %></p>
        </div>

        <div>
          <ul>
            <% post.comments.limit(5).each do |comment| %>
              <li><%= comment.author.name %> : <%= comment.text %></li>
            <% end %>
          </ul>
        </div>
      </li>
    <% end %>
  <% else %>
    <li>
      <div class="post">
        <p>No posts available</p>
      </div>
    </li>
  <% end %>
</ul>

<div class="pandh">
  <%= link_to "Back to Users", users_path, class: "home-link" %>
  <%= link_to "Paginate", user_posts_path(user_id: @user.id, page: params[:page], per_page: @all_posts.size), class: "home-link" %>
  <%= link_to "Back to Posts", user_posts_path(user_id: @user.id), class: "home-link" %>
</div>

app/views/posts/likes/_like.html.erb
<%= button_to like_user_post_path(post.id), method: :post, remote: true, id: 'like-button' do %>
  Like
<% end %>

app/views/posts/new.html.erb
<h2>Add Post</h2>

<%= form_with(model: [@user, @post], url: user_posts_path(@user), method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit 'Create Post' %>
  </div>
<% end %>
<ul>
  <% @post.comments.order(created_at: :desc).limit(10).each do |comment| %>
    <li><%= comment.author.name %> : <%= comment.text %></li>
  <% end %>
</ul>
<div class="pandh">
  <%= link_to "Back to Users", users_path, class: "home-link" %>
  <%= link_to "Back to Posts", user_posts_path(user_id: @user.id), class: "back-link" %>
</div>

app/views/posts/show.html.erb
<div class="post">
  <h1><%= @post.title %></h1>
  <p><%= @post.text %></p>
  <%= render partial: 'posts/likes/like', locals: { post: @post } %>
  <p>Comments: <%= @post.comments_counter %></p>
</div>

<div class="post-comment">
  <%= render "comments/new" %>
  <p>Likes: <%= @post.likes_counter %></p>
</div>

<ul>
  <% @post.comments.order(created_at: :desc).limit(10).each do |comment| %>
    <li><%= comment.author.name %> : <%= comment.text %></li>
  <% end %>
</ul>

<div class="pandh">
  <%= link_to "Back to Users", users_path, class: "home-link" %>
  <%= link_to "Back to Posts", user_posts_path(user_id: @user.id), class: "back-link" %>
</div>

app/views/users/index.html.erb
<head>
  <link rel="stylesheet" href="<%= asset_path('application.css') %>">
</head>
<%= link_to "Add Post", new_user_post_path(user_id: current_user.id), class: "add-post-button" %>
<ul>
  <% @users.each do |user| %>
    <li>
      <div class="user-profile">
        <% if user.photo.present? %>
          <%= image_tag user.photo, alt: "Profile Picture", width: "100", height: "100" %>
        <% else %>
          <p>No Profile Picture</p>
        <% end %>
      </div>
      <div class="user-info">
        <%= link_to user.name, user_path(user) %>
        <p>Number of posts: <%= user.posts_counter %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %>
<li>
  <div class="user-profile">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, alt: "Profile Picture", width: "120", height: "130" %>
    <% else %>
      <p>No Profile Picture</p>
    <% end %>
  </div>

  <div class="user-info">
    <h3><%= @user.name %></h3>
    <p>Number of posts: <%= @user.posts.count %></p>
  </div>
</li>

<div class="bio">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<ul>
  <% if @user.posts.present? %>
    <% @user.posts.limit(3).each_with_index do |post, index| %>
      <li>
        <div class="post">
          <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
            <h4><%= post.title %></h4>

          <% end %>
          <p><%= post.text %></p>
          <p>Likes: <%= post.likes_counter %></p>
          <p>Comments: <%= post.comments_counter %></p>
        </div>
      </li>
    <% end %>
  <% else %>
    <li>
      <div class="post">
        <p>No posts available</p>
      </div>
    </li>
  <% end %>
</ul>

<div class="buttons">
<%= link_to "See All Posts", user_posts_path(user_id: @user.id), class: "home-link" %>
<%= link_to "Back to Users", users_path, class: "home-link" %>
</div>